### ISSUE TITLE
[BUG] Inconsistency of `cmath.log()` with Cpython

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/pocketpy#212]
Thanks for taking the time to fill out a bug report!
Please provide a descriptive title above and fill in the following fields.

### Bug description
You can paste sources here that may cause the error.

Snippet -
```
import cmath
z = 10 + 5j
z_log = cmath.log(z)
print(z_log)
```

Python 3.9 -
```
C:\Users\kunni\pocketpy>python try.py
(2.4141568686511508+0.4636476090008061j)
```

Pocketpy main - 
```
C:\Users\kunni\pocketpy>main try.py
Traceback (most recent call last):
  File "try.py", line 3
    z_log = cmath.log(z)
  File "cmath.py", line 102, in log
    return math.log(z.__abs__(), base) + phase(z) * 1j
TypeError: expected 1 arguments, got 2
```

**Comment by blueloveTH** [comment]
Very helpful. Thank you :)
