### ISSUE TITLE
[BUG] Support sign in integer casting of strings

### ISSUE THREAD

**Issue by faze-geek** [pocketpy/pocketpy#214]
I came across this inconsistency when I was playing around with some basic benchmarks.
### Bug description
Pocketpy main
```
>>> a = int('123')
>>> a
123
>>> a = int('-123')
Traceback (most recent call last):
  File "<stdin>", line 1
    a = int('-123')
ValueError: invalid literal for int(): '-123'
>>>
>>> a = int('+123')
Traceback (most recent call last):
  File "<stdin>", line 1
    a = int('+123')
ValueError: invalid literal for int(): '+123'
```

**Comment by faze-geek** [comment]
Considering this as a bug towards consistency of code as float conversion already supports this -
```
>>> a = float('-3.14')
>>> a
-3.14
>>> a = float('+3.14')
>>> a
3.14
```

**Comment by blueloveTH** [comment]
Very helpful~ Thank you :)
